# ZKeys
# Copyright 2025 Julio Merino

name: install

on: push

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Install mtree
              run: |
                  sudo apt update
                  sudo apt install --yes mtree-netbsd
            - name: Install
              env:
                  PREFIX: ${{ runner.temp }}/zkeys-prefix
              run: make install PREFIX="${PREFIX}"
            - name: Verify installed layout
              env:
                  PREFIX: ${{ runner.temp }}/zkeys-prefix
              run: mtree -f install.mtree -p "${PREFIX}"
